---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrator(orchestrator)
	price_agent(price_agent)
	news_agent(news_agent)
	event_classifier(event_classifier)
	eval_agent(eval_agent)
	synthesis_agent(synthesis_agent)
	guardrail_output(guardrail_output)
	confidence_gate(confidence_gate)
	hitl_gate_1(hitl_gate_1)
	hitl_gate_2(hitl_gate_2)
	rewrite_question(rewrite_question)
	supervisor(supervisor)
	answer_composer(answer_composer)
	__end__([<p>__end__</p>]):::last
	__start__ --> orchestrator;
	__start__ --> rewrite_question;
	answer_composer --> guardrail_output;
	confidence_gate -.-> __end__;
	confidence_gate -.-> hitl_gate_1;
	eval_agent --> answer_composer;
	eval_agent -.-> hitl_gate_2;
	eval_agent -.-> synthesis_agent;
	event_classifier -.-> __end__;
	event_classifier -.-> eval_agent;
	guardrail_output -.-> __end__;
	guardrail_output -.-> confidence_gate;
	guardrail_output -.-> synthesis_agent;
	news_agent --> answer_composer;
	news_agent --> event_classifier;
	orchestrator --> news_agent;
	orchestrator --> price_agent;
	price_agent --> answer_composer;
	price_agent --> event_classifier;
	rewrite_question --> supervisor;
	supervisor --> eval_agent;
	supervisor --> news_agent;
	supervisor --> price_agent;
	synthesis_agent --> guardrail_output;
	hitl_gate_1 --> __end__;
	hitl_gate_2 --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
