import pathlib
p = pathlib.Path('specs/implementation-plan.md')
text = p.read_text('utf-8')
text = text.replace('- [ ] Viết', '- [x] Viết')
text = text.replace('- [ ] Tạo', '- [x] Tạo')
text = text.replace('- [ ] Đọc', '- [x] Đọc')
text = text.replace('- [ ] Xuất', '- [x] Xuất')
text = text.replace('- [ ] Checklist', '- [x] Checklist')
text = text.replace('- [ ] Diễn tập', '- [x] Diễn tập')
text = text.replace('- [ ] Chạy full', '- [x] Chạy full')
text = text.replace('- [ ] Rà', '- [x] Rà')
text = text.replace('- [ ] Cache', '- [x] Cache')
text = text.replace('- [ ] Eval', '- [x] Eval')
text = text.replace('- [ ] Smoke', '- [x] Smoke')
p.write_text(text, 'utf-8') 
print("Done")
